UNIT MENU;

{$mode ObjFPC}{$H+}

INTERFACE

USES
  Classes, SysUtils,CRT, ABMC_TERRENO, ABMC_PERSONAS, ARCHIVO_PERSONAS, ARCHIVO_TERRENO, USA_ARCH_PERSONA, USA_ARCH_TERRENO, ARBOL_PERSONA, OTROS_PROC2;
PROCEDURE CATASTROMENU();
PROCEDURE ABMC_TERRENOS(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP; VAR RAIZDNI:T_PUNT; VAR RAIZNOM:T_PUNT);
PROCEDURE ABMC_PROPIETARIOS(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP; VAR RAIZDNI:T_PUNT; VAR RAIZNOM:T_PUNT);
PROCEDURE LISTA_COMPROBANTES(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP; VAR RAIZDNI:T_PUNT; VAR RAIZNOM:T_PUNT);
PROCEDURE ESTADISTICAS(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP);
IMPLEMENTATION
PROCEDURE CATASTROMENU();
VAR
    OP:CHAR;
    ERROR:BOOLEAN;
    OP2,AC:BYTE;
    RAIZDNI:T_PUNT;
    RAIZNOM:T_PUNT;
    ARCHT:T_ARCHIVO_TERR;
    ARCHP:T_ARCHIVO_PROP;
    I:INTEGER;

BEGIN
  //CREAS DOS ARBOLES;
  CREAR_ARBOL(RAIZDNI);
  CREAR_ARBOL(RAIZNOM);
  //CREAS ARCHIVOS;
  CREAR_T(ARCHT);
  CREAR_P(ARCHP);
  ABRIR_T(ARCHT);
  ABRIR_P(ARCHP);
  ABRIR_ARBOL(ARCHP,RAIZNOM,RAIZDNI);
  IF FILESIZE(ARCHT)>=2 THEN ORDENAR_TERRENO(ARCHT);
  CANTIDAD_BAJA2(ARCHP);
  REPEAT
    CLRSCR;
    TEXTBACKGROUND(WHITE);
    TEXTCOLOR(BLACK);
    GOTOXY(43,7);
    WRITELN('             MENU PRINCIPAL                 ');
    TEXTBACKGROUND(BLACK);
    TEXTCOLOR(WHITE);
    GOTOXY(43,11);
    WRITELN('1 - TERRENOS');
    GOTOXY(43,12);
    WRITELN('2 - PROPIETARIOS');
    GOTOXY(43,13);
    WRITELN('3 - LISTADOS Y COMPROBANTE');
    GOTOXY(43,14);
    WRITELN(UTF8TOANSI('4 - ESTADÍSTICAS'));
    GOTOXY(43,15);
    WRITELN('0 - SALIR');
    AC:=1;
    REPEAT
       IF AC=2 THEN
       BEGIN
         GOTOXY(43,16);
         WRITELN('                                        ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,17);
         WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;
       GOTOXY(43,16);
       READLN(OP);
       IF NOT(TRYSTRTOINT(OP,I)) THEN
        BEGIN
             GOTOXY(43,16);
             WRITELN('                                        ');
             TEXTBACKGROUND(RED);
             GOTOXY(43,17);
             WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
             TEXTBACKGROUND(BLACK);
             ERROR:=TRUE;
          END
          ELSE
          BEGIN
          STRTOINT(OP);
          OP2:=STRTOINT(OP);
          END;
          AC:=2;
    UNTIL ((OP2=0) OR (OP2=1) OR (OP2=2) OR (OP2=3) OR (OP2=4)) AND (ERROR=FALSE);
    CLRSCR;
    CASE OP2 OF
    1: ABMC_TERRENOS(ARCHT,ARCHP,RAIZDNI,RAIZNOM);
    2: ABMC_PROPIETARIOS(ARCHT,ARCHP,RAIZDNI,RAIZNOM);
    3: LISTA_COMPROBANTES(ARCHT,ARCHP,RAIZDNI,RAIZNOM);
    4: ESTADISTICAS(ARCHT,ARCHP);
    END;

  UNTIL OP2 = 0 ;
END;
PROCEDURE ABMC_TERRENOS(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP; VAR RAIZDNI:T_PUNT; VAR RAIZNOM:T_PUNT);
VAR
    I:INTEGER;
   OP:STRING;
   ERROR:BOOLEAN;
   OP2,AC:BYTE;
BEGIN
  CLRSCR;

  REPEAT
    CLRSCR;
    TEXTBACKGROUND(WHITE);
    TEXTCOLOR(BLACK);
    GOTOXY(43,7);
    WRITELN(UTF8TOANSI(' MENU ALTA - BAJA - MODIFICACIÓN - CONSULTA '));
    TEXTBACKGROUND(BLACK);
    TEXTCOLOR(WHITE);
    GOTOXY(43,11);
    WRITELN('1 - ALTA TERRENO');
    GOTOXY(43,12);
    WRITELN('2 - BAJA TERRENO');
    GOTOXY(43,13);
    WRITELN('3 - MODIFICAR TERRENO');
    GOTOXY(43,14);
    WRITELN('4 - CONSULTAR TERRENO');
    GOTOXY(43,15);
    WRITELN('0 - VOLVER A MENU PRINCIPAL');
    AC:=1;
    REPEAT
       IF AC=2 THEN
       BEGIN
         GOTOXY(43,16);
         WRITELN('                                        ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,17);
         WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;

          GOTOXY(43,16);
          READLN(OP);
          IF NOT (TRYSTRTOINT(OP,I)) THEN
          BEGIN
             GOTOXY(43,16);
             WRITELN('                                        ');
             TEXTBACKGROUND(RED);
             GOTOXY(43,17);
             WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
             TEXTBACKGROUND(BLACK);
             ERROR:=TRUE;
          END
          ELSE
          BEGIN
            STRTOINT(OP);
            OP2:=STRTOINT(OP);
          END;
       AC:=2;
    UNTIL ((OP2=0) OR (OP2=1) OR (OP2=2) OR (OP2=3) OR (OP2=4)) AND (ERROR=FALSE);

    CLRSCR;

    CASE OP2 OF
    1: ALTA_TERRENO(ARCHT,ARCHP,RAIZDNI,RAIZNOM);
    2: BAJA_TERRENO(ARCHT,ARCHP);
    3: MODIFICAR_TERRENO(ARCHT);
    4: CONSULTA_TERRENO(ARCHT);
    END;

  UNTIL OP2 = 0 ;
  CLRSCR;
END;

PROCEDURE ABMC_PROPIETARIOS(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP; VAR RAIZDNI:T_PUNT; VAR RAIZNOM:T_PUNT);
VAR
   I:INTEGER;
   OP:STRING;
   ERROR:BOOLEAN;
   OP2,AC:BYTE;
BEGIN
  CLRSCR;
  REPEAT
    CLRSCR;
    TEXTBACKGROUND(WHITE);
    TEXTCOLOR(BLACK);
    GOTOXY(43,7);
    WRITELN(UTF8TOANSI(' MENU ALTA - BAJA - MODIFICACIÓN - CONSULTA '));
    TEXTBACKGROUND(BLACK);
    TEXTCOLOR(WHITE);
    GOTOXY(43,11);
    WRITELN('1 - ALTA PROPIETARIO');
    GOTOXY(43,12);
    WRITELN('2 - BAJA PROPIETARIO');
    GOTOXY(43,13);
    WRITELN('3 - MODIFICAR PROPIETARIO');
    GOTOXY(43,14);
    WRITELN('4 - CONSULTAR PROPIETARIO');
    GOTOXY(43,15);
    WRITELN('0 - VOLVER A MENU PRINCIPAL');
    AC:=1;
    REPEAT
       IF AC=2 THEN
       BEGIN
         GOTOXY(43,16);
         WRITELN('                                        ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,17);
         WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;
        IF NOT (TRYSTRTOINT(OP,I)) THEN
            BEGIN
             GOTOXY(43,16);
             WRITELN('                                        ');
             TEXTBACKGROUND(RED);
             GOTOXY(43,17);
             WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
             TEXTBACKGROUND(BLACK);
             ERROR:=TRUE;
            END
        ELSE
         BEGIN
          STRTOINT(OP);
          OP2:=STRTOINT(OP);
         END;
       AC:=2;
    UNTIL ((OP2=0) OR (OP2=1) OR (OP2=2) OR (OP2=3) OR (OP2=4)) AND (ERROR=FALSE);
    CLRSCR;

    CASE OP2 OF

    1: ALTA_PERSONA(RAIZNOM,RAIZDNI,ARCHP);
    2: BAJA_PERSONA(RAIZNOM,RAIZDNI, ARCHP, ARCHT );
    3: MODIFICAR_PERSONA(ARCHP, RAIZDNI, RAIZNOM);
    4: CONSULTAR_PERSONA(ARCHP,RAIZDNI,RAIZNOM);

    END;

  UNTIL OP2 = 0 ;
  CLRSCR;
END;

PROCEDURE LISTA_COMPROBANTES(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP; VAR RAIZDNI:T_PUNT; VAR RAIZNOM:T_PUNT);
VAR
   I:INTEGER;
   OP:STRING;
   ERROR:BOOLEAN;
   OP2,AC:BYTE;
BEGIN
    CLRSCR;

    REPEAT
      CLRSCR;
      TEXTBACKGROUND(WHITE);
      TEXTCOLOR(BLACK);
      GOTOXY(43,7);
      WRITELN(UTF8TOANSI('          LISTADOS Y COMPROBANTE          '));
      TEXTBACKGROUND(BLACK);
      TEXTCOLOR(WHITE);
      GOTOXY(43,11);
      WRITELN('1 - LISTADO POR NOMBRE Y APELLIDO CON TERRENOS VALORIZADOS');
      GOTOXY(43,12);
      WRITELN('2 - LISTADO DE INSCRIPCIONES DE UN ',UTF8TOANSI('AÑO'),', ORDENADO POR FECHA');
      GOTOXY(43,13);
      WRITELN('3 - LISTADO DE TERRENOS ORDENADO POR ZONA');
      GOTOXY(43,14);
      WRITELN('4 - COMPROBANTE DE TERRENO');
      GOTOXY(43,15);
      WRITELN('0 - VOLVER A MENU PRINCIPAL');
      AC:=1;
      REPEAT
       IF AC=2 THEN
       BEGIN
          GOTOXY(43,16);
          WRITELN('                                        ');
          TEXTBACKGROUND(RED);
          GOTOXY(43,17);
          WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
          TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;
          GOTOXY(43,16);
          READLN(OP);
          IF NOT (TRYSTRTOINT(OP,I)) THEN
           BEGIN
             GOTOXY(43,16);
             WRITELN('                                        ');
             TEXTBACKGROUND(RED);
             GOTOXY(43,17);
             WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
             TEXTBACKGROUND(BLACK);
             ERROR:=TRUE;
          END
          ELSE
          BEGIN
          STRTOINT(OP);
          OP2:=STRTOINT(OP);
          END;
       AC:=2;
    UNTIL ((OP2=0) OR (OP2=1) OR (OP2=2) OR (OP2=3) OR (OP2=4)) AND (ERROR=FALSE);
    CASE OP2 OF
      1: LISTADO_APYNOM(RAIZNOM,ARCHT,ARCHP);
      2: LISTADO_POR_FECHA(ARCHT);
      3: LISTADO_ZONA(ARCHT);
      4: COMPROBANTE(ARCHT,ARCHP);
    END;

  UNTIL OP2=0 ;
  CLRSCR;
END;

PROCEDURE ESTADISTICAS(VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP);
VAR
   I:INTEGER;
   OP:STRING;
   ERROR:BOOLEAN;
   OP2,AC:BYTE;
BEGIN


  REPEAT
    CLRSCR;
    TEXTBACKGROUND(WHITE);
    TEXTCOLOR(BLACK);
    GOTOXY(43,7);
    WRITELN(UTF8TOANSI('            MENU DE ESTADÍSTICAS            '));
    TEXTBACKGROUND(BLACK);
    TEXTCOLOR(WHITE);
    GOTOXY(43,11);
    WRITELN('1 - CANTIDAD DE INSCRIPTOS ENTRE DOS FECHAS');
    GOTOXY(43,12);
    WRITELN(UTF8TOANSI('2 - PORCENTAJE DE PERSONAS CON MÁS DE UN TERRENO'));
    GOTOXY(43,13);
    WRITELN(UTF8TOANSI('3 - PORCENTAJE DE TERRENOS POR TIPO DE EDIFICACIÓN'));
    GOTOXY(43,14);
    WRITELN('4 - CANTIDAD DE PERSONAS DADAS DE BAJA');
    GOTOXY(43,15);
    WRITELN('0 - VOLVER A MENU PRINCIPAL');
    AC:=1;
    REPEAT
       IF AC=2 THEN
       BEGIN
          GOTOXY(43,16);
          WRITELN('                                        ');
          TEXTBACKGROUND(RED);
          GOTOXY(43,17);
          WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
          TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;
       GOTOXY(43,16);
       READLN(OP);
       IF NOT (TRYSTRTOINT(OP,I)) THEN
       BEGIN
             GOTOXY(43,16);
             WRITELN('                                        ');
             TEXTBACKGROUND(RED);
             GOTOXY(43,17);
             WRITELN('LA OPCION INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
             TEXTBACKGROUND(BLACK);
             ERROR:=TRUE;
       END
       ELSE
       BEGIN
          STRTOINT(OP);
          OP2:=STRTOINT(OP);
       END;
       AC:=2;
    UNTIL ((OP2=0) OR (OP2=1) OR (OP2=2) OR (OP2=3) OR (OP2=4)) AND (ERROR=FALSE);
    CLRSCR;

    CASE OP2 OF
    1: DOS_FECHAS(ARCHT);
    2: PORCENTAJE_PROP(ARCHT,ARCHP);
    3: PORCENTAJE_EDIF(ARCHT);
    4: CANTIDAD_BAJA();
    END;

  UNTIL OP2 = 0 ;
  CLRSCR;
END;

END.



END.

