UNIT OTROS_PROC2;

{$mode ObjFPC}{$H+}

INTERFACE

USES
  Classes, SysUtils, crt, ARCHIVO_TERRENO, ARCHIVO_PERSONAS, ARBOL_PERSONA, ABMC_PERSONAS, USA_ARCH_PERSONA, USA_ARCH_TERRENO;


PROCEDURE LISTADO_APYNOM(VAR RAIZ:T_PUNT; VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP);
PROCEDURE LISTADO_POR_FECHA(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE LISTADO_ZONA(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE COMPROBANTE(VAR ARCHT:T_ARCHIVO_TERR; VAR ARCHP: T_ARCHIVO_PROP);
PROCEDURE DOS_FECHAS(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE PORCENTAJE_PROP(VAR ARCHT:T_ARCHIVO_TERR; VAR ARCHP:T_ARCHIVO_PROP);
PROCEDURE PORCENTAJE_EDIF(VAR ARCHT:T_ARCHIVO_TERR);
PROCEDURE CANTIDAD_BAJA();
PROCEDURE CANTIDAD_BAJA2(VAR ARCH:T_ARCHIVO_PROP);

IMPLEMENTATION
PROCEDURE LISTADO_APYNOM(VAR RAIZ:T_PUNT; VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP);
VAR
  ACGOTOXY:BYTE;
BEGIN
  CLRSCR;
  GOTOXY(43,7);
  WRITELN('LISTADO DE PROPIETARIOS ORDENADO');
  GOTOXY(43,8);
  WRITELN('POR APELLIDO Y NOMBRE, CON SUS RESPECTIVOS TERRENOS');
  GOTOXY(43,11);
  WRITELN(UTF8TOANSI('A CONTINUACIÓN SE MOSTRARA EL LISTADO'));
  GOTOXY(43,12);
  WRITELN('ORDENADO CON PROPIEDADES VALORIZADAS.');
  GOTOXY(43,13);
  WRITELN('PRESIONE UNA TECLA PARA CONTINUAR.');
  GOTOXY(43,14);
  READKEY;
  CLRSCR;
  IF ARBOL_VACIO(RAIZ)=FALSE THEN
  BEGIN
     CLRSCR;
     GOTOXY(43,1);
     WRITELN('LISTADO DE PROPIETARIOS ORDENADO');
     GOTOXY(43,2);
     WRITELN('POR APELLIDO Y NOMBRE, CON SUS RESPECTIVOS TERRENOS');
     GOTOXY(1,4);
     WRITELN('APELLIDO Y NOMBRE |');
     GOTOXY(20,4);
     CAMPOS_T();
     ACGOTOXY:=6;
     INORDEN(RAIZ,ARCHT,ARCHP,ACGOTOXY);
     READKEY;
  END
  ELSE
    BEGIN
        CLRSCR;
        GOTOXY(43,7);
        WRITELN('LISTADO DE PROPIETARIOS ORDENADO');
        GOTOXY(43,8);
        WRITELN('POR APELLIDO Y NOMBRE, CON SUS RESPECTIVOS TERRENOS');
        GOTOXY(43,11);
        WRITELN('NO EXISTEN PROPIETARIOS PARA LISTAR');
        GOTOXY(43,13);
        WRITELN('PRESIONE UNA TECLA PARA CONTINUAR.');
        GOTOXY(43,14);
        READKEY;
    END;
  CLRSCR;
END;
PROCEDURE LISTADO_POR_FECHA(VAR ARCH:T_ARCHIVO_TERR);
VAR
  BUSCAD:STRING;
  X:T_DATO_TERR;
  ANIO:STRING;
  AUX:BOOLEAN;
  AC,AC2,ACGOTOXY,L:BYTE;
  ARCHAUX:T_ARCHIVO_TERR;
  ERROR:BOOLEAN;
  I:INTEGER;

BEGIN
  CLRSCR;
  ASSIGN(ARCHAUX,RUTAAUX);
  REWRITE(ARCHAUX);
  RESET(ARCHAUX);
  ABRIR_T(ARCH);
  GOTOXY(43,7);
  WRITELN(UTF8TOANSI('LISTADO DE INSCRIPCIONES EN UN AÑO, ORDENADAS POR FECHA'));
  AC2:=1;
  REPEAT
       IF AC=2 THEN
         BEGIN
           GOTOXY(79,11);
           WRITELN('              ');
           TEXTBACKGROUND(RED);
           GOTOXY(43,12);
           WRITELN ('LA FECHA INGRESADA ES INVALIDA, INTENTE DE NUEVO.');
           TEXTBACKGROUND(BLACK);
         END;
         ERROR:=FALSE;
         GOTOXY(43,11);
         WRITELN(UTF8TOANSI('INGRESE EL AÑO QUE DESEA CONSULTAR:      (AAAA)'));
         GOTOXY(79,11);
         READLN(BUSCAD);
         IF NOT(TRYSTRTOINT(BUSCAD,I)) THEN
         BEGIN
         GOTOXY(79,11);
         WRITELN('              ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,2);
         WRITELN('LA FECHA INGRESADA ES INVALIDA, INTENTE DE NUEVO.');
         TEXTBACKGROUND(BLACK);
         ERROR:=TRUE;
         END;
         AC:=2;
  UNTIL (ERROR=FALSE);
  AUX:=FALSE;
  SEEK(ARCH,0);
  AC:=1;
  WHILE NOT(EOF(ARCH)) DO
  BEGIN
     READ(ARCH,X);
     ANIO:= COPY(X.FECHA_INSC,0,4);
     IF (ANIO = BUSCAD) THEN
     BEGIN
          AUX:=TRUE;
          CLRSCR;
          SEEK(ARCHAUX,FILESIZE(ARCHAUX));
          WRITE(ARCHAUX,X);
          IF FILESIZE(ARCHAUX)>=2 THEN ORDENAR_ARCHAUX(ARCHAUX);
     END
  END;
  IF AUX=FALSE THEN
  BEGIN
      CLRSCR;
      GOTOXY(43,7);
      WRITELN(UTF8TOANSI('LISTADO DE INSCRIPCIONES DE UN AÑO, ORDENADO POR FECHA'));
      GOTOXY(43,11);
      WRITELN(UTF8TOANSI('NO EXISTEN TERRENOS INSCRIPTOS EN EL AÑO '), BUSCAD);
      GOTOXY(43,14);
      WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
      GOTOXY(43,15);
      READKEY;
      CLRSCR;
  END;
  CLRSCR;
  IF FILESIZE(ARCHAUX)>0 THEN
  BEGIN
  SEEK(ARCHAUX,0);
  ACGOTOXY:=0;
  L:=5;
  GOTOXY(37,1);
  WRITELN(UTF8TOANSI('LISTADO DE INSCRIPCIONES EN UN AÑO, ORDENADAS POR FECHA'));
  WHILE NOT(EOF(ARCHAUX)) DO
  BEGIN
          READ(ARCHAUX,X);
          GOTOXY(8,4);
          CAMPOS_T();
          MOSTRAR_DATOS(X,L);
          L:=L+1;
  END;
  GOTOXY(43,24);
  WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
  GOTOXY(43,25);
  READKEY;
  END;
  CLOSE(ARCHAUX);
  ERASE(ARCHAUX);
  CLRSCR;
  CERRAR_T(ARCH);
END;
PROCEDURE LISTADO_ZONA(VAR ARCH:T_ARCHIVO_TERR);
VAR
  I,L:BYTE;
  X:T_DATO_TERR;
  AUX:BOOLEAN;

BEGIN
  CLRSCR;
  ABRIR_T(ARCH);
  L:=4;
  GOTOXY(40,1);
  WRITELN('LISTADO DE TERRENOS ORDENADO POR ZONA');
  GOTOXY(8,3);
  CAMPOS_T();
  FOR I:=1 TO 5 DO
  BEGIN
   L:=L+1;
   GOTOXY(40,L);
   WRITELN('TERRENOS DE ZONA ', I);
   L:=L+1;
   AUX:=FALSE;
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
      READ(ARCH,X);
      IF (X.ZONA = I) THEN
      BEGIN
        AUX:=TRUE;
        MOSTRAR_DATOS(X,L);
        L:=L+1;
      END;
   END;
   IF (AUX=FALSE) THEN
   BEGIN
     GOTOXY(37,L);
     WRITELN('NO EXISTEN TERRENOS DE LA ZONA ',I);
     L:=L+1;
   END;
  END;
  GOTOXY(37,L+1);
  WRITELN('PRESIONE UNA TECLA PARA CONTINUAR.');
  GOTOXY(37,L+2);
  READKEY;
  CLRSCR;
  CERRAR_T (ARCH);
END;

PROCEDURE DOS_FECHAS(VAR ARCH:T_ARCHIVO_TERR);
VAR F1,F2:STRING;
  X:T_DATO_TERR;
  CONT:BYTE;
  AC,AC2:BYTE;
  ERROR:BOOLEAN;
  I:INTEGER;
BEGIN
  CLRSCR;
  GOTOXY(50,7);
  WRITELN('CANTIDAD DE INSCRIPTOS ENTRE DOS FECHAS');
  AC:=1;
  REPEAT
       IF AC=2 THEN
         BEGIN
           TEXTBACKGROUND(RED);
           GOTOXY(43,12);
           WRITELN ('LA FECHA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
           TEXTBACKGROUND(BLACK);
         END;
         ERROR:=FALSE;
         GOTOXY(43,11);
         WRITELN('INGRESE FECHA DE INICIO:                              (AAAA/MM/DD)');
         GOTOXY(68,11);
         READLN(F1);
         DELETE(F1,5,1);
         DELETE(F1,7,1);
         IF NOT(TRYSTRTOINT(F1,I)) THEN
         BEGIN
         GOTOXY(68,11);
         WRITELN('              ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,12);
         WRITELN('LA FECHA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
         ERROR:=TRUE;
         END ELSE
         BEGIN
         INSERT('/', F1,5);
         INSERT('/', F1,8);
         END;
         AC:=2;
  UNTIL (COPY(F1,5,1)='/') AND (COPY(F1,8,1)='/') AND (STRTOINT(COPY(F1,6,2))<=12) AND (STRTOINT(COPY(F1,6,2))>0) AND (ERROR=FALSE) AND (STRTOINT(COPY(F1,9,2))<=31) AND (STRTOINT(COPY(F1,9,2))>0);
  AC2:=1;
  GOTOXY(43,12);
  WRITELN('                                                 ');
  REPEAT
       IF AC2=2 THEN
         BEGIN
           TEXTBACKGROUND(RED);
           GOTOXY(43,13);
           WRITELN ('LA FECHA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
           TEXTBACKGROUND(BLACK);
         END;
         ERROR:=FALSE;
         GOTOXY(43,12);
         WRITELN('INGRESE FECHA FINAL:                              (AAAA/MM/DD)');
         GOTOXY(64,12);
         READLN(F2);
         DELETE(F2,5,1);
         DELETE(F2,7,1);
         IF NOT(TRYSTRTOINT(F2,I)) THEN
         BEGIN
         GOTOXY(64,12);
         WRITELN('              ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,13);
         WRITELN('LA FECHA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
         ERROR:=TRUE;
         END ELSE
         BEGIN
         INSERT('/', F2,5);
         INSERT('/', F2,8);
         END;
         AC2:=2;
  UNTIL (COPY(F2,5,1)='/') AND (COPY(F2,8,1)='/') AND (STRTOINT(COPY(F2,6,2))<=12) AND (STRTOINT(COPY(F2,6,2))>0) AND (ERROR=FALSE) AND (STRTOINT(COPY(F2,9,2))<=31) AND (STRTOINT(COPY(F2,9,2))>0);
  GOTOXY(43,13);
  WRITELN('                                                           ');
  ABRIR_T(ARCH);
  SEEK(ARCH,0);
  CONT:=0;
  WHILE NOT(EOF(ARCH)) DO
  BEGIN
   READ(ARCH,X);
   IF (X.FECHA_INSC>=F1) AND (X.FECHA_INSC<=F2) THEN CONT:= CONT+1;
  END;
  GOTOXY(43,14);
  WRITELN('LA CANTIDAD DE INSCRIPCIONES ENTRE');
  GOTOXY(43,15);
  WRITELN('ESAS FECHAS FUERON: ',CONT,'.');

GOTOXY(43,17);
  WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
  GOTOXY(43,18);
  READKEY;
  CLRSCR;
END;


PROCEDURE COMPROBANTE(VAR ARCHT:T_ARCHIVO_TERR; VAR ARCHP: T_ARCHIVO_PROP);
VAR
  BUSCADO,BUSCADO2:STRING;
  POS,L,J:BYTE;
  POS2:BYTE;
  X:T_DATO_TERR;
  Y:T_DATO_PROP;
  ENC,ENC2:BOOLEAN;
BEGIN
     CLRSCR;
     ABRIR_T(ARCHT);
     ABRIR_P(ARCHP);
     ENC:=FALSE;
     ENC2:=FALSE;
     GOTOXY(50,7);
     WRITELN('COMPROBANTE');
     GOTOXY(43,11);
     WRITELN('INGRESE EL NUMERO DE PLANO DEL TERRENO');
     GOTOXY(43,12);
     WRITELN('QUE DESEA IMPRIMIR SU COMPROBANTE');
     GOTOXY(43,13);
     READLN(BUSCADO);
     BUSCAR_TERRENO(ARCHT,BUSCADO,POS,ENC);
     IF ENC THEN
     BEGIN
          SEEK(ARCHT,POS);
          READ(ARCHT,X);
          BUSCADO2:= X.NRO_CONTR;
          BUSCAR_ARCH_P(ARCHP,BUSCADO2,POS2,ENC2);
          IF ENC2 THEN
          BEGIN
          SEEK(ARCHP,POS2);
          READ(ARCHP,Y);
          CLRSCR;
          GOTOXY(50,7);
          WRITELN('COMPROBANTE');
          GOTOXY(43,12);
          WRITELN('DATOS DEL TERRENO');
          GOTOXY(8,14);
          CAMPOS_T();
          L:=15;
          MOSTRAR_DATOS(X,L);
          GOTOXY(43,17);
          WRITELN('DATOS DEL PROPIETARIO/A');
          GOTOXY(8,19);
          CAMPOS_PERSONA();
          L:=20;
          MOSTRAR_PERSONA(Y,L);
          GOTOXY(43,25);
          WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
          GOTOXY(43,26);
          READKEY;
          CLRSCR;
          END
          ELSE
          BEGIN
           CLRSCR;
           GOTOXY(50,7);
           WRITELN('COMPROBANTE');
           GOTOXY(43,11);
           WRITELN('NO SE ENCONTRO AL PROPIETARIO/A DEL TERRENO BUSCADO');
           GOTOXY(43,13);
           WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
           GOTOXY(43,14);
           READKEY;
           CLRSCR;
          END;
     END
     ELSE
     BEGIN
          CLRSCR;
          GOTOXY(50,7);
          WRITELN('COMPROBANTE');
          GOTOXY(43,11);
          WRITELN('NO SE ENCONTRO EL TERRENO BUSCADO');
          GOTOXY(43,13);
          WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
          GOTOXY(43,14);
          READKEY;
          CLRSCR;
     END;
END;
PROCEDURE PORCENTAJE_PROP(VAR ARCHT:T_ARCHIVO_TERR; VAR ARCHP:T_ARCHIVO_PROP);
VAR TOTALPERSONAS:BYTE;
    X:T_DATO_TERR;
    Y:T_DATO_PROP;
    AC,AC2:BYTE;
    PORC:REAL;
    AUX:STRING;
BEGIN
   AC2:=0;
   ABRIR_P(ARCHP);
   ABRIR_T(ARCHT);
   TOTALPERSONAS:=FILESIZE(ARCHP);
   SEEK(ARCHP,0);
   WHILE NOT(EOF(ARCHP)) DO
   BEGIN
        CLRSCR;
        AC:=0;
        READ(ARCHP,Y);
        AUX:=Y.NRO_CONTR;
        SEEK(ARCHT,0);
   WHILE NOT(EOF(ARCHT)) DO
   BEGIN
        READ(ARCHT,X);
        IF (X.NRO_CONTR = AUX) THEN
        BEGIN
             AC:=AC+1;
        END;
   END;
   IF (AC>=2) THEN
   BEGIN
      AC2:= AC2 +1;
   END;
   END;
   IF (TOTALPERSONAS>0) THEN
   BEGIN
    PORC:= (AC2*100)/TOTALPERSONAS;
    GOTOXY(50,7);
    WRITELN(UTF8TOANSI('PORCENTAJE DE PERSONAS CON MÁS DE UN TERRENO'));
    GOTOXY(43,11);
    WRITELN(UTF8TOANSI('EL PORCENTAJE DE PERSONAS CON MÁS DE UN TERRENO ES DE: '), FLOATTOSTR(PORC), '%');
    GOTOXY(43,13);
    WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
    GOTOXY(43,14);
   END ELSE
   BEGIN
    GOTOXY(50,7);
    WRITELN(UTF8TOANSI('PORCENTAJE DE PERSONAS CON MÁS DE UN TERRENO'));
    GOTOXY(43,11);
    WRITELN('NO HAY TERRENOS REGISTRADOS');
   END;
   CERRAR_T(ARCHT);
   CERRAR_P(ARCHP);
   READKEY;
   CLRSCR;
END;
PROCEDURE PORCENTAJE_EDIF(VAR ARCHT:T_ARCHIVO_TERR);
VAR AC1,AC2,AC3,AC4,AC5:BYTE;
    X:T_DATO_TERR;
    TOTALTERRENOS:BYTE;
BEGIN
   ABRIR_T(ARCHT);
   IF FILESIZE(ARCHT)<>0 THEN
   BEGIN
   TOTALTERRENOS:= FILESIZE(ARCHT);
   AC1:=0;
   AC2:=0;
   AC3:=0;
   AC4:=0;
   AC5:=0;
   SEEK(ARCHT,0);
   WHILE NOT(EOF(ARCHT)) DO
   BEGIN
        READ(ARCHT,X);
        IF (X.EDIF = 1) THEN AC1:= AC1+1 ELSE
           IF (X.EDIF = 2) THEN AC2:=AC2+1 ELSE
              IF (X.EDIF = 3) THEN AC3:=AC3+1 ELSE
                 IF (X.EDIF = 4) THEN AC4:=AC4+1 ELSE
                    IF (X.EDIF = 5) THEN AC5:=AC5+1;
   END;
   CLRSCR;
   GOTOXY(50,7);
   WRITELN(UTF8TOANSI('PORCENTAJE POR TIPO DE EDIFICACIÓN'));
   GOTOXY(43,11);
   WRITELN(UTF8TOANSI('PORCENTAJE DE TERRENOS CON TIPO DE EDIFICACIÓN 1: '), ROUND(AC1*100/TOTALTERRENOS), '%');
   GOTOXY(43,12);
   WRITELN(UTF8TOANSI('PORCENTAJE DE TERRENOS CON TIPO DE EDIFICACIÓN 2: '), ROUND(AC2*100/TOTALTERRENOS), '%');
   GOTOXY(43,13);
   WRITELN(UTF8TOANSI('PORCENTAJE DE TERRENOS CON TIPO DE EDIFICACIÓN 3: '), ROUND(AC3*100/TOTALTERRENOS), '%');
   GOTOXY(43,14);
   WRITELN(UTF8TOANSI('PORCENTAJE DE TERRENOS CON TIPO DE EDIFICACIÓN 4: '), ROUND(AC4*100/TOTALTERRENOS), '%');
   GOTOXY(43,15);
   WRITELN(UTF8TOANSI('PORCENTAJE DE TERRENOS CON TIPO DE EDIFICACIÓN 5: '), ROUND(AC5*100/TOTALTERRENOS), '%');
   GOTOXY(43,17);
   WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
   GOTOXY(43,18);
   READKEY;
   CLRSCR;
   END ELSE
   BEGIN
       CLRSCR;
       GOTOXY(50,7);
       WRITELN(UTF8TOANSI('PORCENTAJE POR TIPO DE EDIFICACIÓN'));
       GOTOXY(43,11);
       WRITELN('NO HAY TERRENOS CARGADOS.');
       GOTOXY(43,13);
       WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
       GOTOXY(43,14);
       READKEY;
       CLRSCR;
   END;
END;
 PROCEDURE CANTIDAD_BAJA();
BEGIN
     CLRSCR;
     GOTOXY(50,7);
     WRITELN('CANTIDAD DE PERSONAS DADAS DE BAJA');
     GOTOXY(43,11);
     WRITELN('LA CANTIDAD DE PERSONAS DADAS DE BAJA SON: ', BAJAS);
     GOTOXY(43,13);
     WRITELN('PRESIONE UNA TECLA PARA CONTINUAR');
     GOTOXY(43,14);
     READKEY;
     CLRSCR;
END;

 PROCEDURE CANTIDAD_BAJA2(VAR ARCH:T_ARCHIVO_PROP);
 VAR
     X:T_DATO_PROP;
 BEGIN
   ABRIR_P(ARCH);
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
        READ(ARCH,X);
        IF X.ESTADO = FALSE THEN
        BAJAS:=BAJAS+1;
   END;
   CERRAR_P(ARCH);
 END;

 END.




end.

