unit USA_ARCH_TERRENO;

INTERFACE                                               //UNIT CON PROCEDIMIENTOS QUE MODIFICAN A LOS TERRENOS

USES
  CLASSES, CRT, SYSUTILS, ARCHIVO_TERRENO;

CONST
   RUTAAUX = 'C:\ARCHIVOS\ARCHIVOTERRENOSAUX.dat';
   RUTAAUX1 = 'C:\ARCHIVOS\ARCHIVOTERRENOSAUX2.dat';


PROCEDURE CARGAR_TERRENO(VAR X:T_DATO_TERR);
PROCEDURE ORDENAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE ORDENAR_ARCHAUX(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE CAMPOS_T();
PROCEDURE MOSTRAR_DATOS(VAR X:T_DATO_TERR;VAR Y:BYTE);
PROCEDURE ELIMINAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR;VAR POS:BYTE);
PROCEDURE BUSCAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR;BUSCADO:STRING;VAR POS:BYTE;VAR ENC:BOOLEAN);
PROCEDURE BUSCAR_TERRENO_CONTR(VAR ARCH:T_ARCHIVO_TERR;BUSCADO:STRING;VAR NOM:STRING;VAR ACGOTOXY:BYTE);
PROCEDURE VALORIZAR(VAR X:T_DATO_TERR);
PROCEDURE MOSTRAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR);

IMPLEMENTATION

PROCEDURE CARGAR_TERRENO( VAR X:T_DATO_TERR);                           //PROCEDIMIENTO PARA CARGAR DATOS DE TERRENOS EN REG
VAR
  ZONA2,EDIF2:STRING;
  ERROR:BOOLEAN;
  I:INTEGER;
  AC:1..2;
BEGIN
  CLRSCR;
  GOTOXY(50,7);
  WRITELN('ALTA DE TERRENO');
  WITH X DO
  BEGIN
     GOTOXY(43,12);
     WRITELN('PLANO:');
     GOTOXY(50,12);
     READLN(NRO_PLANO);
     GOTOXY(43,13);
     WRITELN(UTF8TOANSI('DOMICILIO PARCELARIO:'));
     GOTOXY(65,13);
     READLN(DOM_PARC);
     AC:=1;
     REPEAT
       IF AC=2 THEN
         BEGIN
           TEXTBACKGROUND(RED);
           GOTOXY(43,15);
           WRITELN ('LA FECHA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
           TEXTBACKGROUND(BLACK);
         END;
         ERROR:=FALSE;
         GOTOXY(43,14);
         WRITELN('FECHA DE INSCRIPCION:                                   (AAAA/MM/DD)');
         GOTOXY(64,14);
         READLN(FECHA_INSC);
         DELETE(FECHA_INSC,5,1);
         DELETE(FECHA_INSC,7,1);
         IF NOT(TRYSTRTOINT(FECHA_INSC,I)) THEN
         BEGIN
         TEXTBACKGROUND(RED);
         GOTOXY(43,15);
         WRITELN('LA FECHA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
         ERROR:=TRUE;
         END
         ELSE
         BEGIN
         INSERT('/', FECHA_INSC,5);
         INSERT('/', FECHA_INSC,8);
         END;
         AC:=2;
     UNTIL (COPY(FECHA_INSC,5,1)='/') AND (COPY(FECHA_INSC,8,1)='/') AND (STRTOINT(COPY(FECHA_INSC,6,2))<=12) AND (STRTOINT(COPY(FECHA_INSC,6,2))>0) AND (ERROR=FALSE) AND (STRTOINT(COPY(FECHA_INSC,9,2))<=31) AND (STRTOINT(COPY(FECHA_INSC,9,2))>0);
     GOTOXY(43,15);
     WRITELN('SUPERFICIE:                                                        ');
     GOTOXY(55,15);
     READLN(SUP);
     AC := 1;
     REPEAT
       IF AC = 2 THEN
       BEGIN
            GOTOXY(49,16);
            WRITELN('                                        ');
            TEXTBACKGROUND(RED);
            GOTOXY(43,17);
            WRITELN('LA ZONA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
            TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;
       GOTOXY(43,16);
       WRITELN('ZONA:');
       GOTOXY(49,16);
       READLN(ZONA2);
       IF NOT(TRYSTRTOINT(ZONA2,I)) THEN
         BEGIN
         GOTOXY(49,16);
         WRITELN('                                        ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,17);
         WRITELN('LA ZONA INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
         ERROR:=TRUE;
         END
       ELSE
       BEGIN
          STRTOINT(ZONA2);
          ZONA:=STRTOINT(ZONA2);
       END;
       AC:=2;
    UNTIL ((ZONA=0) OR (ZONA=1) OR (ZONA=2) OR (ZONA=3) OR (ZONA=4) OR (ZONA=5)) AND (ERROR=FALSE);
    GOTOXY(43,17);
    WRITELN('                                                       ');
    AC:=1;
    REPEAT
       IF AC = 2 THEN
       BEGIN
         GOTOXY(57,17);
         WRITELN('                                        ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,18);
         WRITELN(UTF8TOANSI('LA EDIFICACIÓN INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.'));
         TEXTBACKGROUND(BLACK);
       END;
       ERROR:=FALSE;
       GOTOXY(43,17);
       WRITELN(UTF8TOANSI('EDIFICACIÓN:'));
       GOTOXY(57,17);
       READLN(EDIF2);
       IF NOT(TRYSTRTOINT(EDIF2,I)) THEN
        BEGIN
             GOTOXY(57,17);
             WRITELN('                                        ');
             TEXTBACKGROUND(RED);
             GOTOXY(43,18);
             WRITELN(UTF8TOANSI('LA EDIFICACIÓN INGRESADA ES INVALIDA, INTENTE NUEVAMENTE.'));
             TEXTBACKGROUND(BLACK);
             ERROR:=TRUE;
          END
       ELSE
       BEGIN
       STRTOINT(EDIF2);
       EDIF:=STRTOINT(EDIF2);
       END;
       AC:=2;
    UNTIL ((EDIF=0) OR (EDIF=1) OR (EDIF=2) OR (EDIF=3) OR (EDIF=4) OR (EDIF=5)) AND (ERROR=FALSE);
    GOTOXY(43,18);
    WRITELN('                                                             ');
    GOTOXY(43,18);
    WRITELN(UTF8TOANSI('NÚMERO DE CONTRIBUYENTE: '),X.NRO_CONTR);
  END;
END;
PROCEDURE ORDENAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR);                      //ORDENAMIENTO BURBUJA  DEL ARCHIVO
VAR
  I,J:BYTE;
  X,Y,AUX:T_DATO_TERR;
BEGIN
   FOR I:=0 TO FILESIZE(ARCH)-2 DO
   BEGIN
      FOR J:=0 TO FILESIZE(ARCH)-2 DO
      BEGIN
         SEEK(ARCH,J);
         READ(ARCH,X);
         READ(ARCH,Y);
         IF (X.NRO_CONTR+X.FECHA_INSC)>(Y.NRO_CONTR+Y.FECHA_INSC) THEN
         BEGIN
            SEEK(ARCH,J);
            WRITE(ARCH,Y);
            WRITE(ARCH,X);
         END;
      END;
   END;

END;

PROCEDURE ORDENAR_ARCHAUX(VAR ARCH:T_ARCHIVO_TERR);                      //ORDENAMIENTO BURBUJA  DEL ARCHIVO
VAR
  I,J:BYTE;
  X,Y,AUX:T_DATO_TERR;
BEGIN
   FOR I:=0 TO FILESIZE(ARCH)-2 DO
   BEGIN
      FOR J:=0 TO FILESIZE(ARCH)-2 DO
      BEGIN
         SEEK(ARCH,J);
         READ(ARCH,X);
         READ(ARCH,Y);
         IF (X.FECHA_INSC)>(Y.FECHA_INSC) THEN
         BEGIN
            SEEK(ARCH,J);
            WRITE(ARCH,Y);
            WRITE(ARCH,X);
         END;
      END;
   END;

END;

PROCEDURE CAMPOS_T();
BEGIN
  WRITELN(UTF8TOANSI('N° CONTRIB | N° PLANO | FECHA DE INSCRIPCIÓN |   AVALÚO   |  DOMICILIO | SUPERFICIE | ZONA | EDIFICACIÓN '));
END;

PROCEDURE MOSTRAR_DATOS(VAR X:T_DATO_TERR;VAR Y:BYTE);                           //MUESTRA UN REG
BEGIN
  WITH X DO
  BEGIN
  GOTOXY(15,Y);
  WRITELN('', NRO_CONTR);
  GOTOXY(24,Y);
  WRITELN('', NRO_PLANO);
  GOTOXY(34,Y);
  WRITELN('', FECHA_INSC);
  GOTOXY(52,Y);
  WRITELN('$', FLOATTOSTR(AVALUO));
  GOTOXY(66,Y);
  WRITELN('', DOM_PARC);
  GOTOXY(81,Y);
  WRITELN('', FLOATTOSTR(SUP));
  GOTOXY(92,Y);
  WRITELN('', ZONA);
  GOTOXY(102,Y);
  WRITELN('', EDIF);
  END;
END;

PROCEDURE ELIMINAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR;VAR POS:BYTE);       //ELIMINA UN DATOS DE UN REG
VAR
  J:BYTE;
  X:T_DATO_TERR;
  ARCHAUX:T_ARCHIVO_TERR;
BEGIN
  ASSIGN(ARCHAUX,RUTAAUX);
  REWRITE(ARCHAUX);
  ABRIR_T(ARCHAUX);
  WHILE NOT(EOF(ARCH)) DO
  BEGIN
  IF (FILEPOS(ARCH)=POS) THEN
   BEGIN
    READ(ARCH,X);
   END
  ELSE
   BEGIN
    READ(ARCH,X);
    WRITE(ARCHAUX,X);
   END;
  END;
  CLOSE(ARCH);
  ERASE(ARCH);
  ASSIGN(ARCH, RUTA1);
  REWRITE(ARCH);
  SEEK(ARCHAUX,0);
  WHILE NOT(EOF(ARCHAUX)) DO
  BEGIN
    READ(ARCHAUX,X);
    WRITE(ARCH,X);
  END;
  CLOSE(ARCHAUX);
  ERASE(ARCHAUX);
END;

PROCEDURE BUSCAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR;BUSCADO:STRING;VAR POS:BYTE;VAR ENC:BOOLEAN);
VAR
  X:T_DATO_TERR;
BEGIN
  SEEK(ARCH,0);
  WHILE NOT(EOF(ARCH)) DO
  BEGIN
       READ(ARCH,X);
        IF (X.NRO_PLANO = BUSCADO) THEN
        BEGIN
          POS:= FILEPOS(ARCH)-1;
          ENC:=TRUE;
        END
  END;
END;

PROCEDURE BUSCAR_TERRENO_CONTR(VAR ARCH:T_ARCHIVO_TERR;BUSCADO:STRING;VAR NOM:STRING;VAR ACGOTOXY:BYTE);
VAR
  X:T_DATO_TERR;
  AC,L,J:BYTE;
BEGIN
  AC:=0;
  SEEK(ARCH,0);
  WHILE NOT(EOF(ARCH)) DO
  BEGIN
       READ(ARCH,X);
       IF (X.NRO_CONTR = BUSCADO) THEN
       BEGIN
          IF AC=0 THEN
          BEGIN
            GOTOXY(1,ACGOTOXY);
            WRITELN(' ',NOM);
          END;
          MOSTRAR_DATOS(X,ACGOTOXY);
          ACGOTOXY:=ACGOTOXY+1;
          AC:=AC+1;
       END;
  END;
END;

PROCEDURE MOSTRAR_TERRENO(VAR ARCH:T_ARCHIVO_TERR);
VAR
   X:T_DATO_TERR;
BEGIN
  RESET(ARCH);
  SEEK(ARCH,0);
  WHILE NOT(EOF(ARCH)) DO
  BEGIN
    READ(ARCH,X);
   // MOSTRAR_DATOS(X);
    READKEY;
  END;
  READKEY;
END;

PROCEDURE VALORIZAR(VAR X:T_DATO_TERR);
VAR
  PORCENTZONA,PORCENTEDIF:REAL;
BEGIN
   WITH X DO
   BEGIN

   IF ZONA=1 THEN PORCENTZONA:=1.5 ELSE
    IF ZONA=2 THEN PORCENTZONA:=1.1 ELSE
      IF ZONA=3 THEN PORCENTZONA:=0.7 ELSE
        IF ZONA=4 THEN PORCENTZONA:=0.4 ELSE PORCENTZONA:=0.1 ;

  IF EDIF=1 THEN PORCENTEDIF:=1.7 ELSE
    IF EDIF=2 THEN PORCENTEDIF:=1.3 ELSE
      IF EDIF=3 THEN PORCENTEDIF:=1.1 ELSE
        IF EDIF=4 THEN PORCENTEDIF:=0.8 ELSE PORCENTEDIF:=0.5;

  AVALUO:= (12308.60*SUP)*PORCENTZONA*PORCENTEDIF;

  END;
END;

END.



