UNIT USA_ARCH_PERSONA;

INTERFACE                                                   //UNIT CON PROCEDIMIENTOS PARA MODIFICAR A LOS PROPIETARIOS/AS

USES
  CLASSES, CRT, SYSUTILS, ARCHIVO_PERSONAS;

CONST
  RUTAAUX= 'C:\ARCHIVOS\ARCHIVOAUX.dat';

PROCEDURE CARGAR_PERSONA(VAR X:T_DATO_PROP);
PROCEDURE CAMPOS_PERSONA();
PROCEDURE MOSTRAR_PERSONA(VAR Z:T_DATO_PROP; VAR Y:BYTE);
PROCEDURE BUSCAR_ARCH_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
PROCEDURE BUSCAR_ARCH_DNI_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
PROCEDURE BUSCAR_ARCH_DNI2_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
PROCEDURE BUSCAR_ARCH_NOM_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
PROCEDURE AGREGAR_PERSONA(VAR ARCH:T_ARCHIVO_PROP; VAR X:T_DATO_PROP);

 IMPLEMENTATION
PROCEDURE CARGAR_PERSONA(VAR X:T_DATO_PROP);                 //CARGAR DATOS EN REG DE PERSONAS
VAR
  AC:1..2;
  I:INTEGER;
  ERROR:BOOLEAN;
BEGIN
  WITH X DO
  BEGIN
     GOTOXY(43,12);
     WRITELN('NOMBRE:');
     GOTOXY(51,12);
     READLN(NOM);
     GOTOXY(43,13);
     WRITELN('APELLIDO:');
     GOTOXY(53,13);
     READLN(AP);
     GOTOXY(43,14);
     WRITELN(UTF8TOANSI('DIRECCIÓN:'));
     GOTOXY(54,14);
     READLN(DIR);
     GOTOXY(43,15);
     WRITELN('CIUDAD:');
     GOTOXY(51,15);
     READLN(CIUDAD);
     AC:=1;
     REPEAT
       IF AC=2 THEN
         BEGIN
           TEXTBACKGROUND(RED);
           GOTOXY(43,17);
           WRITELN ('LA FECHA NO ES VALIDA, INTENTE NUEVAMENTE.');
           TEXTBACKGROUND(BLACK);
         END;
         ERROR:=FALSE;
         GOTOXY(43,16);
         WRITELN('FECHA DE NACIMIENTO:                                   (AAAA/MM/DD)');
         GOTOXY(64,16);
         READLN(FECHA_NAC);
         DELETE(FECHA_NAC,5,1);
         DELETE(FECHA_NAC,7,1);
         IF NOT(TRYSTRTOINT(FECHA_NAC,I)) THEN
         BEGIN
         GOTOXY(64,16);
         WRITELN('              ');
         TEXTBACKGROUND(RED);
         GOTOXY(43,17);
         WRITELN('LA FECHA NO ES VALIDA, INTENTE NUEVAMENTE.');
         TEXTBACKGROUND(BLACK);
         ERROR:=TRUE;
         END
         ELSE
         BEGIN
         INSERT('/', FECHA_NAC,5);
         INSERT('/', FECHA_NAC,8);
         END;
         AC:=2;
     UNTIL (COPY(FECHA_NAC,5,1)='/') AND (COPY(FECHA_NAC,8,1)='/') AND (STRTOINT(COPY(FECHA_NAC,6,2))<=12) AND (STRTOINT(COPY(FECHA_NAC,6,2))>0) AND (ERROR=FALSE) AND (STRTOINT(COPY(FECHA_NAC,9,2))<=31) AND (STRTOINT(COPY(FECHA_NAC,9,2))>0) AND (STRTOINT(COPY(FECHA_NAC,9,2))>0);
     GOTOXY(43,17);
     WRITELN(UTF8TOANSI('TELÉFONO:                                             '));
     GOTOXY(53,17);
     READLN(TEL);
     GOTOXY(43,18);
     WRITELN('EMAIL:');
     GOTOXY(50,18);
     READLN(EMAIL);
     GOTOXY(43,19);
     WRITELN(UTF8TOANSI('NÚMERO DE CONTRIBUYENTE: '),X.NRO_CONTR);
     ESTADO:=TRUE;
  END;
END;
 PROCEDURE CAMPOS_PERSONA();
 BEGIN
    WRITELN(UTF8TOANSI('N° CONTRIB |   DNI   | APELLIDO | NOMBRE |  DIRECCIÓN  |  CIUDAD  | NACIMIENTO | TELÉFONO | EMAIL'));
 END;

 PROCEDURE MOSTRAR_PERSONA(VAR Z:T_DATO_PROP; VAR Y:BYTE);          //MOSTRAR DATOS DE UN REG DE PERSONAS

 BEGIN
 WITH Z DO
   BEGIN
   GOTOXY(15,Y);
   WRITELN('',NRO_CONTR);
   GOTOXY(20,Y);
   WRITELN('',DNI);
   GOTOXY(30,Y);
   WRITELN('',AP);
   GOTOXY(41,Y);
   WRITELN('',NOM);
   GOTOXY(50,Y);
   WRITELN('',DIR);
   GOTOXY(64,Y);
   WRITELN('',CIUDAD);
   GOTOXY(76,Y);
   WRITELN('',FECHA_NAC);
   GOTOXY(88,Y);
   WRITELN('',TEL);
   GOTOXY(99,Y);
   WRITELN('',EMAIL);
   END;
 END;

 PROCEDURE BUSCAR_ARCH_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
 VAR
   X:T_DATO_PROP;
 BEGIN
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
         READ(ARCH,X);
         IF (X.NRO_CONTR = BUSCADO) AND (X.ESTADO=TRUE) THEN
         BEGIN
           POS:= FILEPOS(ARCH)-1;
           ENC:=TRUE;
         END;
   END
 END;

 PROCEDURE BUSCAR_ARCH_DNI_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
 VAR
   X:T_DATO_PROP;
 BEGIN
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
         READ(ARCH,X);
         IF (X.DNI = BUSCADO) AND (X.ESTADO=TRUE) THEN
         BEGIN
           POS:= FILEPOS(ARCH)-1;
           ENC:=TRUE;
         END;
   END
 END;

 PROCEDURE BUSCAR_ARCH_DNI2_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
 VAR
   X:T_DATO_PROP;
 BEGIN
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
         READ(ARCH,X);
         IF (X.DNI = BUSCADO) THEN
         BEGIN
           POS:= FILEPOS(ARCH)-1;
           ENC:=TRUE;
         END;
   END
 END;

 PROCEDURE BUSCAR_ARCH_NOM_P(VAR ARCH:T_ARCHIVO_PROP;VAR BUSCADO:STRING;VAR POS:BYTE; VAR ENC:BOOLEAN);
 VAR
   X:T_DATO_PROP;
   NOM:STRING;
 BEGIN
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
         READ(ARCH,X);
         NOM:=CONCAT(X.AP+' '+X.NOM);
         IF (NOM = BUSCADO) AND (X.ESTADO=TRUE) THEN
         BEGIN
           POS:= FILEPOS(ARCH)-1;
           ENC:=TRUE;
         END;
   END
 END;

 PROCEDURE AGREGAR_PERSONA(VAR ARCH:T_ARCHIVO_PROP; VAR X:T_DATO_PROP);
 BEGIN
   SEEK(ARCH, FILESIZE(ARCH));
   WRITE(ARCH,X);
 END;

END.
