unit ARBOL_PERSONA;

interface

uses
  CRT,ARCHIVO_PERSONAS, ARCHIVO_TERRENO, USA_ARCH_PERSONA, USA_ARCH_TERRENO;
TYPE
T_PUNT=^T_NODO;

T_NODO=RECORD
 CLAVE:STRING;
 SAI:T_PUNT;
 SAD:T_PUNT;
 END;

PROCEDURE CREAR_ARBOL (VAR RAIZ:T_PUNT);
PROCEDURE ABRIR_ARBOL(VAR ARCH:T_ARCHIVO_PROP; VAR RAIZNOM:T_PUNT; VAR RAIZDNI:T_PUNT);
PROCEDURE AGREGAR_ARBOL(VAR RAIZ:T_PUNT; X:STRING);
FUNCTION ARBOL_VACIO (RAIZ:T_PUNT): BOOLEAN;
FUNCTION PREORDEN(RAIZ:T_PUNT; X:STRING):T_PUNT;
PROCEDURE INORDEN(VAR RAIZ:T_PUNT;VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP;VAR ACGOTOXY:BYTE);
FUNCTION ELIMINAR_MIN (VAR RAIZ:T_PUNT):STRING;
PROCEDURE ELIMINAR_ARBOL(VAR RAIZ:T_PUNT; X:STRING);

implementation
PROCEDURE CREAR_ARBOL (VAR RAIZ:T_PUNT);
BEGIN
 RAIZ:= NIL;
END;
PROCEDURE ABRIR_ARBOL(VAR ARCH:T_ARCHIVO_PROP; VAR RAIZNOM:T_PUNT; VAR RAIZDNI:T_PUNT);
VAR
   X:T_DATO_PROP;                                                                                      //PROCEDIMIENTO PARA QUE CUANDO COMIENZE EL PROGRAMA
   NOM:STRING;                                                                                    //CARGE LOS DATOS DEL ARCHIVO DE PERSONAS EN LOS ARBOLES
BEGIN
   ABRIR_P(ARCH);
   SEEK(ARCH,0);
   WHILE NOT(EOF(ARCH)) DO
   BEGIN
      READ(ARCH,X);
      IF X.ESTADO=TRUE THEN
      BEGIN
         NOM:=CONCAT(X.AP+' '+X.NOM);
         AGREGAR_ARBOL(RAIZNOM,NOM);
         AGREGAR_ARBOL(RAIZDNI,X.DNI);
      END;
   END;
   CERRAR_P(ARCH);
END;

PROCEDURE AGREGAR_ARBOL(VAR RAIZ: T_PUNT;X:STRING);
BEGIN
 IF RAIZ=NIL THEN
  BEGIN
    NEW(RAIZ);
    RAIZ^.CLAVE:= X;
    RAIZ^.SAI:= NIL;
    RAIZ^.SAD:= NIL;
  END
  ELSE
   IF (RAIZ^.CLAVE) > (X) THEN AGREGAR_ARBOL(RAIZ^.SAI,X)
   ELSE AGREGAR_ARBOL(RAIZ^.SAD,X)
END;
FUNCTION ARBOL_VACIO (RAIZ:T_PUNT): BOOLEAN;
BEGIN
 ARBOL_VACIO:= RAIZ = NIL;
END;
FUNCTION PREORDEN(RAIZ:T_PUNT;X:STRING):T_PUNT;
BEGIN
IF (RAIZ = NIL) THEN
 PREORDEN := NIL
ELSE
 IF (( RAIZ^.CLAVE) = (X)) THEN
   PREORDEN:= RAIZ
 ELSE
  IF (RAIZ^.CLAVE) > (X) THEN
   PREORDEN := PREORDEN(RAIZ^.SAI,X)
  ELSE
  PREORDEN := PREORDEN(RAIZ^.SAD,X)
END;

PROCEDURE INORDEN(VAR RAIZ:T_PUNT;VAR ARCHT:T_ARCHIVO_TERR;VAR ARCHP:T_ARCHIVO_PROP;VAR ACGOTOXY:BYTE);
VAR
  J:STRING;
  Y:T_DATO_TERR;
  X:T_DATO_PROP;
  BUSCADO:STRING;
  POS:BYTE;
  NRO_CONTR:STRING;
  ENC:BOOLEAN;

BEGIN
  IF RAIZ <> NIL THEN
  BEGIN
     ABRIR_T(ARCHT);
     ABRIR_P(ARCHP);
     INORDEN(RAIZ^.SAI, ARCHT, ARCHP,ACGOTOXY);
     J:= RAIZ^.CLAVE;
     ENC:=FALSE;
     BUSCAR_ARCH_NOM_P(ARCHP,J,POS,ENC);
     SEEK(ARCHP,POS);
     READ(ARCHP,X);
     BUSCADO:=X.NRO_CONTR;
     BUSCAR_TERRENO_CONTR(ARCHT,BUSCADO,J,ACGOTOXY);
     INORDEN(RAIZ^.SAD, ARCHT, ARCHP,ACGOTOXY);
  END
END;

FUNCTION ELIMINAR_MIN (VAR RAIZ:T_PUNT):STRING;
BEGIN
     IF RAIZ^.SAI = NIL THEN
     BEGIN
          ELIMINAR_MIN := RAIZ^.CLAVE ;
          RAIZ := RAIZ^.SAD ;
     END
     ELSE ELIMINAR_MIN:=ELIMINAR_MIN(RAIZ^.SAI);
END;

PROCEDURE ELIMINAR_ARBOL (VAR RAIZ:T_PUNT ; X:STRING);
BEGIN
     IF RAIZ<>NIL THEN
     BEGIN
          IF (X) < (RAIZ^.CLAVE) THEN
          ELIMINAR_ARBOL(RAIZ^.SAI,X)
          ELSE
            IF (X) > (RAIZ^.CLAVE) THEN
                 ELIMINAR_ARBOL(RAIZ^.SAD,X)
            ELSE
                 IF (RAIZ^.SAI=NIL) AND (RAIZ^.SAD=NIL) THEN
                      RAIZ:=NIL
                 ELSE
                      IF RAIZ^.SAI = NIL THEN
                         RAIZ:=RAIZ^.SAD
                      ELSE
                          IF RAIZ^.SAD = NIL THEN
                             RAIZ:=RAIZ^.SAI
                          ELSE
                          RAIZ^.CLAVE:=ELIMINAR_MIN(RAIZ^.SAD);
     END;
END;


END.

