unit ARCHIVO_PERSONAS;
interface

uses
  CRT,Classes, SysUtils;
CONST RUTA='C:\ARCHIVOS\ARCHIVO_PERSONAS.dat';
TYPE
T_DATO_PROP=RECORD         //DATO1(ARCHIVO DE PROPIETARIOS)
   NRO_CONTR:STRING[10];
   AP:STRING[20];
   NOM:STRING[30];
   DIR:STRING[20];
   CIUDAD:STRING[20];
   DNI:STRING[10];
   FECHA_NAC:STRING[10];
   TEL:STRING[13];
   EMAIL:STRING[30];
   ESTADO:BOOLEAN;
END;

T_ARCHIVO_PROP=FILE OF T_DATO_PROP;  //DEFINICION DE ARCHIVOS

PROCEDURE CREAR_P(VAR ARCH:T_ARCHIVO_PROP);
PROCEDURE ABRIR_P(VAR ARCH:T_ARCHIVO_PROP);
PROCEDURE CERRAR_P(VAR ARCH:T_ARCHIVO_PROP);
IMPLEMENTATION

PROCEDURE CREAR_P(VAR ARCH:T_ARCHIVO_PROP);
BEGIN
ASSIGN(ARCH, RUTA);
REWRITE(ARCH);
 END;

PROCEDURE ABRIR_P(VAR ARCH:T_ARCHIVO_PROP);
BEGIN
 ASSIGN(ARCH,RUTA);
 RESET(ARCH)
END;

PROCEDURE CERRAR_P(VAR ARCH:T_ARCHIVO_PROP);
BEGIN
CLOSE(ARCH);
END;
END.
