unit ARCHIVO_TERRENO  ;
INTERFACE
uses crt,classes, sysUtils;
CONST RUTA1='C:\ARCHIVOS\ARCHIVO_TERRENO.dat';
type
T_DATO_TERR=RECORD           //DATO2(ARCHIVO DE TERRENOS)
   NRO_CONTR:STRING[10];
   NRO_PLANO:STRING[10];
   AVALUO:REAL;
   FECHA_INSC:STRING[10];
   DOM_PARC:STRING[50];
   SUP: REAL;
   ZONA: 1..5;
   EDIF: 1..5;
end;
  T_ARCHIVO_TERR=FILE OF T_DATO_TERR;

PROCEDURE ABRIR_T(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE CREAR_T(VAR ARCH:T_ARCHIVO_TERR);
PROCEDURE CERRAR_T(VAR ARCH:T_ARCHIVO_TERR);

IMPLEMENTATION

PROCEDURE ABRIR_T(VAR ARCH:T_ARCHIVO_TERR);          //ABRIR ARCHIVO DE TERRENO
BEGIN
     ASSIGN(ARCH, RUTA1);
     RESET(ARCH);
END;

PROCEDURE CREAR_T(VAR ARCH:T_ARCHIVO_TERR);          //CREAR ARCHIVO DE TERRENO
BEGIN
  ASSIGN(ARCH,RUTA1);
  REWRITE(ARCH);
END;

PROCEDURE CERRAR_T(VAR ARCH:T_ARCHIVO_TERR);         //CERRAR ARCHIVO DE TERRENO
BEGIN
   CLOSE(ARCH);
END;

END.


